version: '3.9'

services:

  mysql:
    image: mysql:8.4
    container_name: board-manager-db

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: board
      MYSQL_USER: board
      MYSQL_PASSWORD: board

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
